// src/models/Payment.model.js
const mongoose = require("mongoose");

const paymentSchema = new mongoose.Schema(
  {
    userId:         { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
    subscriptionId: { type: mongoose.Schema.Types.ObjectId, ref: "Subscription", default: null, index: true },
    orderId:        { type: mongoose.Schema.Types.ObjectId, ref: "Order", default: null },

    // Your internal reference — generated by backend
    referenceNumber: { type: String, unique: true, sparse: true, trim: true, index: true },

    // Zoho identifiers
    zohoSessionId:  { type: String, default: null },
    zohoPaymentId:  { type: String, default: null, index: true },

    // Money
    amount:         { type: Number, required: true },
    amountCaptured: { type: Number, default: 0 },
    amountRefunded: { type: Number, default: 0 },
    feeAmount:      { type: Number, default: 0 },
    netAmount:      { type: Number, default: 0 },
    currency:       { type: String, default: "INR" },

    // Status — mirrors Zoho status values
    status: {
      type: String,
      enum: ["pending", "processing", "succeeded", "failed", "canceled", "refunded"],
      default: "pending",
      index: true,
    },

    // What was paid for
    purpose: {
      type: String,
      enum: ["subscription", "product", "renewal"],
      required: true,
    },

    description:    { type: String, default: null },
    receiptEmail:   { type: String, default: null },
    paymentMethod:  { type: String, default: null },  // upi, card, netbanking etc

    // Metadata array — [{key, value}]
    metaData: [
      {
        key:   { type: String },
        value: { type: String },
      },
    ],

    paidAt:      { type: Date, default: null },
    rawResponse: { type: mongoose.Schema.Types.Mixed, default: null }, // full Zoho response
  },
  { timestamps: true, versionKey: false }
);

paymentSchema.index({ userId: 1, createdAt: -1 });

module.exports = mongoose.model("Payment", paymentSchema);